### ISSUE TITLE
Out of Memory Exception: Adding New Item

### ISSUE THREAD

**Issue by SamuelSVD** [SamuelSVD/TrayDir#225]
When adding a new item and there already exist many items within an instance. a slight delay in the display causes an out of memory exception.

Out of memory. 
   at System.Drawing.Graphics.FromHdcInternal(IntPtr hdc) 
   at System.Drawing.Font.GetHeight() 
   at System.Drawing.Font.get_Height() 
   at System.Windows.Forms.Control.get_FontHeight() 
   at System.Windows.Forms.TextBoxBase.get_PreferredHeight() 
   at System.Windows.Forms.TextBoxBase.get_DefaultSize() 
   at System.Windows.Forms.Control..ctor(Boolean autoInstallSyncContext) 
   at System.Windows.Forms.TextBoxBase..ctor() 
   at System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t) 
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t) 
   at System.Windows.Forms.Control.WndProcException(Exception e) 
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg) 
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context) 
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context) 
   at TrayDir.Program.Main(String[] args)

**Comment by SamuelSVD** [comment]
Unhandled exception.
Out of memory.
   at System.Drawing.Graphics.FromHdcInternal(IntPtr hdc)
   at System.Drawing.Font.ToLogFont(Object logFont)
   at System.Drawing.Font.ToHfont()
   at System.Windows.Forms.Control.FontHandleWrapper..ctor(Font font)
   at System.Windows.Forms.OwnerDrawPropertyBag.get_FontHandle()
   at System.Windows.Forms.TreeView.CustomDraw(Message& m)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.Control.SendMessage(Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.Control.ReflectMessageInternal(IntPtr hWnd, Message& m)
   at System.Windows.Forms.Control.WmNotify(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Control.DefWndProc(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd, Int32 msg, Int32 wParam, Int32 lParam)
   at System.Windows.Forms.Control.SendMessage(Int32 msg, Int32 wparam, Int32 lparam)
   at System.Windows.Forms.TreeView.ForceScrollbarUpdate(Boolean delayed)
   at System.Windows.Forms.TreeNode.UpdateNode(Int32 mask)
   at System.Windows.Forms.TreeNode.set_Text(String value)
   at TrayDir.ITreePathNode.Refresh() in C:\Programming\samverApps\TrayDir\TrayDir\src\views\ITreeNode\ITreePathNode.cs:line 29
   at TrayDir.ITreeViewForm.Rebuild() in C:\Programming\samverApps\TrayDir\TrayDir\src\forms\ITreeViewForm.cs:line 181
   at TrayDir.IView.Rebuild() in C:\Programming\samverApps\TrayDir\TrayDir\src\views\IView.cs:line 50
   at TrayDir.ITreeViewForm.newDocButton_Click(Object sender, EventArgs e) in C:\Programming\samverApps\TrayDir\TrayDir\src\forms\ITreeViewForm.cs:line 211
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at TrayDir.Program.Main(String[] args) in C:\Programming\samverApps\TrayDir\TrayDir\src\Program.cs:line 28

**Comment by SamuelSVD** [comment]
Looks like it might be something within ITreeViewForm.Rebuild

**Comment by SamuelSVD** [comment]
Fixed! Looks like for some reason updating the font on every module caused issues. The fix was to only update the font on the nodes that are not visible
